name: Ruff
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
        with:
          src: ${{ git diff --name-only $CI_MERGE_REQUEST_DIFF_BASE_SHA -- '*.py' }}

